# Generated by Django 4.2 on 2023-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="mqtt_topic",
            field=models.CharField(max_length=50, verbose_name="MQTT topic"),
        ),
        migrations.AlterField(
            model_name="home",
            name="name",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="householdmembership",
            name="relationship",
            field=models.CharField(
                choices=[("owner", "Owner"), ("guest", "Guest")],
                default="owner",
                max_length=5,
            ),
        ),
    ]
