# Generated by Django 4.2 on 2023-04-15 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="home",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.home"
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="devices.devicetype"
            ),
        ),
    ]
