# Generated by Django 4.2 on 2023-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mqtt_topic",
            field=models.CharField(max_length=50, verbose_name="MQTT topic"),
        ),
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
