# Generated by Django 4.2 on 2023-04-15 19:11

from django.db import migrations, models
import django.db.models.deletion
import timescale.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("power", "Power (W)"),
                            ("energy_t", "Energy total (kWh)"),
                            ("energy_c", "Energy cheias (kWh)"),
                            ("energy_p", "Energy ponta (kWh)"),
                            ("energy_v", "Energy vazio (kWh)"),
                            ("tariff", "Active tariff"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[("float", "Float"), ("string", "String")],
                        default="float",
                        max_length=6,
                    ),
                ),
                ("mqtt_topic", models.CharField(max_length=50)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="devices.device"
                    ),
                ),
            ],
            options={
                "verbose_name": "metric",
                "verbose_name_plural": "metric",
            },
        ),
        migrations.CreateModel(
            name="StringMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="metrics.metric"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FloatMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("value", models.FloatField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="metrics.metric"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
