# Generated by Django 4.2 on 2023-04-15 21:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="floatmeasurement",
            options={
                "verbose_name": "measurement (float)",
                "verbose_name_plural": "measurements (float)",
            },
        ),
        migrations.AlterModelOptions(
            name="stringmeasurement",
            options={
                "verbose_name": "measurement (string)",
                "verbose_name_plural": "measurements (string)",
            },
        ),
        migrations.AddField(
            model_name="metric",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="metric",
            name="type",
            field=models.CharField(
                choices=[
                    ("power", "Power (W)"),
                    ("energy_t", "Energy total (kWh)"),
                    ("energy_c", "Energy cheias (kWh)"),
                    ("energy_p", "Energy ponta (kWh)"),
                    ("energy_v", "Energy vazio (kWh)"),
                    ("tariff", "Active tariff"),
                    ("voltage", "Voltage (V)"),
                    ("frequency", "Frequency (Hz)"),
                    ("current", "Frequency (A)"),
                ],
                max_length=10,
            ),
        ),
    ]
